sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: FutureYL030928

  redis:
    host: localhost
    port: 6379
    password: FutureYL030928


  

  wechat:
    appid: wxed80237664c4f669
    secret: 4def09af9dcac742336b8f9e4b01d4cc
    mchid: test
    mchSerialNo: test
    privateKeyFilePath: test
    apiV3Key: test
    weChatPayCertFilePath: test
    notifyUrl: test
    refundNotifyUrl: test

  shop:
    address: xxx